[tool.poetry]
name = "test-ocr"
version = "0.1.0"
description = ""
authors = ["Julius Dehner <julius.dehner@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
PyQt5 = "^5.15.6"
pyscreenshot = "^3.0"
Pillow = "^8.3.1"
numpy = "^1.21.1"
pytesseract = "^0.3.8"
pyperclip = "^1.8.2"
pykakasi = "^2.2.1"
deep-translator = "^1.5.0"
gTTS = "^2.2.3"
pydub = "^0.25.1"
notify-py = "^0.3.3"
typer = "^0.3.2"
pynput = "^1.7.3"
xlib = "^0.21"
playsound = "^1.3.0"
appdirs = "^1.4.4"
SoundCard = "^0.4.1"
scipy = "^1.7.3"
tomli = "^2.0.0"
tomli-w = "^1.0.0"

[tool.poetry.dev-dependencies]
PyQt5-stubs = "^5.15.2"
mypy = "^0.910"
types-Pillow = "^8.3.1"
pyinstaller = "^4.5.1"
flake8 = "*"
types-toml = "*"
flake8-bugbear = "*"
flake8-builtins = "*"
flake8-logging-format = "*"
tox = "*"
pytest = "*"
flake8-executable = "*"
flake8-pytest-style = "*"
flake8-simplify = "*"
flake8-comprehensions = "*"
flake8-pie = "*"
flake8-mypy = "^17.8.0"
black = "*"
appdirs-stubs = "^0.1.0"


[tool.black]
line-length = 120


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
