[tool.poetry]
name = "migaku-ocr-japanese"
version = "0.1.0"
description = ""
authors = ["Julius Dehner <julius.dehner@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.2"
pyscreenshot = "^2.2"
keyboard = "^0.13.5"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.black]
line-length = 120
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
